#!/usr/bin/env python3
"""Tests for README rendering functions in render_status.py."""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from render_status import build_dependency_graph, topological_sort_lps, render_project_readme, render_landing_readme, write_with_frontmatter_preservation


class TestBuildDependencyGraph:
    def test_simple_chain(self):
        """R-001 <- D-001 <- Plan.x"""
        status = {
            "artifacts": [
                {"id": "Plan.x", "type": "plan", "status": "draft", "depends_on": ["D-001"]},
            ],
            "research_findings": [
                {"id": "R-001", "title": "Research", "status": "reviewed"},
            ],
            "decisions": [
                {"id": "D-001", "title": "Decision", "status": "accepted", "based_on": ["R-001"]},
            ],
        }
        result = build_dependency_graph(status)
        assert "R-001" in result
        assert "D-001" in result
        assert "Plan.x" in result
        assert "\u2190" in result  # ← character

    def test_no_dependencies(self):
        """Single artifact with no deps."""
        status = {
            "artifacts": [
                {"id": "R-001", "type": "research", "status": "draft", "depends_on": []},
            ],
            "research_findings": [],
            "decisions": [],
        }
        result = build_dependency_graph(status)
        assert "R-001" in result

    def test_empty_artifacts(self):
        """No artifacts at all."""
        status = {"artifacts": [], "research_findings": [], "decisions": []}
        result = build_dependency_graph(status)
        assert "\u65e0\u4f9d\u8d56\u5173\u7cfb" in result  # 无依赖关系


class TestTopologicalSortLps:
    def test_linear_chain(self):
        """LP-001 -> LP-002 -> LP-003"""
        artifacts = [
            {"id": "LP-003", "type": "landing_prompt", "depends_on": ["LP-002"]},
            {"id": "LP-001", "type": "landing_prompt", "depends_on": ["Plan.x"]},
            {"id": "LP-002", "type": "landing_prompt", "depends_on": ["LP-001"]},
        ]
        result = topological_sort_lps(artifacts)
        assert result == ["LP-001", "LP-002", "LP-003"]

    def test_no_lps(self):
        """No landing prompts in artifacts."""
        artifacts = [
            {"id": "Plan.x", "type": "plan", "depends_on": []},
        ]
        result = topological_sort_lps(artifacts)
        assert result == []

    def test_single_lp(self):
        """One LP with no LP dependencies."""
        artifacts = [
            {"id": "LP-001", "type": "landing_prompt", "depends_on": ["Plan.x"]},
        ]
        result = topological_sort_lps(artifacts)
        assert result == ["LP-001"]

    def test_cycle_fallback_to_sorted(self):
        """Cycle between LPs falls back to alphabetical."""
        artifacts = [
            {"id": "LP-002", "type": "landing_prompt", "depends_on": ["LP-001"]},
            {"id": "LP-001", "type": "landing_prompt", "depends_on": ["LP-002"]},
        ]
        result = topological_sort_lps(artifacts)
        # Cycle detected - fallback to sorted by ID
        assert result == ["LP-001", "LP-002"]


class TestRenderProjectReadme:
    def test_full_output_structure(self, tmp_path):
        """Verify all sections are present in output."""
        # Create directory structure
        (tmp_path / "research").mkdir()
        (tmp_path / "research" / "R-001-test.md").write_text("x")
        (tmp_path / "decisions").mkdir()
        (tmp_path / "decisions" / "D-001-test.yaml").write_text("x")
        (tmp_path / "plan").mkdir()
        (tmp_path / "prompts" / "landing").mkdir(parents=True)
        (tmp_path / "prompts" / "test").mkdir(parents=True)
        (tmp_path / "status").mkdir()
        (tmp_path / "views").mkdir()
        (tmp_path / "tools").mkdir()

        status = {
            "meta": {
                "project_name": "TestProject",
                "last_updated": "2026-05-18T00:00:00Z",
                "total_artifacts": 2,
                "total_research": 1,
                "total_blockers": 0,
            },
            "artifacts": [
                {"id": "Plan.x", "type": "plan", "status": "draft",
                 "path": "plan/x.md", "depends_on": ["D-001"]},
            ],
            "research_findings": [
                {"id": "R-001", "title": "Research", "status": "reviewed",
                 "path": "research/R-001-test.md"},
            ],
            "decisions": [
                {"id": "D-001", "title": "Decision", "status": "accepted",
                 "path": "decisions/D-001-test.yaml", "based_on": ["R-001"]},
            ],
            "handoff_contexts": [],
            "blockers": [],
        }

        result = render_project_readme(status, tmp_path)

        assert "# TestProject \u2014 Project State Overview" in result
        assert "Auto-generated by project-state-tracker" in result
        assert "## \u76ee\u5f55\u7ed3\u6784" in result
        assert "research/" in result
        assert "## Artifact \u72b6\u6001\u603b\u89c8" in result
        assert "R-001" in result
        assert "## \u4f9d\u8d56\u5173\u7cfb\u56fe" in result
        assert "## Handoff \u4e0a\u4e0b\u6587" in result
        assert "\u65e0\u6d3b\u8dc3 handoff" in result
        assert "## Blockers" in result
        assert "\u65e0\u963b\u585e\u9879" in result
        assert "## \u5feb\u901f\u5bfc\u822a" in result

    def test_with_blockers(self, tmp_path):
        """Blockers section shows open blockers."""
        for d in ["research", "decisions", "plan", "status", "views", "tools"]:
            (tmp_path / d).mkdir(parents=True, exist_ok=True)
        (tmp_path / "prompts" / "landing").mkdir(parents=True)
        (tmp_path / "prompts" / "test").mkdir(parents=True)

        status = {
            "meta": {"project_name": "T", "last_updated": "2026-01-01",
                     "total_artifacts": 0, "total_research": 0, "total_blockers": 1},
            "artifacts": [],
            "research_findings": [],
            "decisions": [],
            "handoff_contexts": [],
            "blockers": [
                {"id": "B-001", "title": "Missing API", "severity": "high",
                 "status": "open", "blocks": ["LP-001"]},
            ],
        }

        result = render_project_readme(status, tmp_path)
        assert "B-001" in result
        assert "Missing API" in result


class TestRenderLandingReadme:
    def test_generates_full_file_when_no_existing(self, tmp_path):
        """When no README exists, generates front-matter + body."""
        (tmp_path / "prompts" / "landing").mkdir(parents=True)

        status = {
            "meta": {
                "project_name": "TestProject",
                "last_updated": "2026-05-18T00:00:00Z",
                "source_root": "Q:\\TestProject",
                "scope": ["Q:\\TestProject", "Q:\\TestProject\\Docs"],
                "pst_root": "Q:\\TestProject\\Docs",
                "coding_standards": "Use 4-space indent.",
            },
            "artifacts": [
                {"id": "LP-001", "type": "landing_prompt", "status": "ready",
                 "depends_on": ["Plan.x"], "produces_handoffs": ["HC-001"]},
                {"id": "LP-002", "type": "landing_prompt", "status": "draft",
                 "depends_on": ["LP-001"], "produces_handoffs": []},
            ],
            "handoff_contexts": [
                {"id": "HC-001", "producer": "LP-001", "version": 1,
                 "status": "available",
                 "facts": ["fact one", "fact two"],
                 "constraints": ["must not break API"],
                 "consumed_by": ["LP-002"]},
            ],
        }

        result = render_landing_readme(status, tmp_path)

        # Front-matter
        assert result.startswith("---\n")
        assert "source_root:" in result
        assert "Q:\\TestProject" in result
        assert "pst_root:" in result
        # Body
        assert "## LP \u5e8f\u5217" in result
        assert "LP-001 -> LP-002" in result
        assert "## Coding Standards" in result
        assert "Use 4-space indent." in result
        assert "## \u5f53\u524d LP \u72b6\u6001" in result
        assert "## Handoff \u4e0a\u4e0b\u6587\u6458\u8981" in result
        assert "fact one; fact two" in result

    def test_no_source_root_marks_unconfigured(self, tmp_path):
        """Missing source_root produces placeholder."""
        (tmp_path / "prompts" / "landing").mkdir(parents=True)

        status = {
            "meta": {"project_name": "T", "last_updated": "2026-01-01"},
            "artifacts": [],
            "handoff_contexts": [],
        }

        result = render_landing_readme(status, tmp_path)
        assert "<\u672a\u914d\u7f6e>" in result

    def test_no_lps_shows_message(self, tmp_path):
        """No LP artifacts shows placeholder message."""
        (tmp_path / "prompts" / "landing").mkdir(parents=True)

        status = {
            "meta": {"project_name": "T", "last_updated": "2026-01-01",
                     "source_root": "/src"},
            "artifacts": [
                {"id": "Plan.x", "type": "plan", "status": "draft", "depends_on": []},
            ],
            "handoff_contexts": [],
        }

        result = render_landing_readme(status, tmp_path)
        assert "\u5c1a\u65e0\u5df2\u6ce8\u518c\u7684 Landing Prompt" in result

    def test_no_coding_standards_omits_section(self, tmp_path):
        """Missing coding_standards means no section generated."""
        (tmp_path / "prompts" / "landing").mkdir(parents=True)

        status = {
            "meta": {"project_name": "T", "last_updated": "2026-01-01",
                     "source_root": "/src"},
            "artifacts": [],
            "handoff_contexts": [],
        }

        result = render_landing_readme(status, tmp_path)
        assert "## Coding Standards" not in result


class TestFrontmatterPreservation:
    def test_preserves_existing_frontmatter(self, tmp_path):
        """Existing front-matter is kept, body from new content is used."""
        readme = tmp_path / "README.md"
        readme.write_text(
            '---\nsource_root: "Q:\\\\Custom"\nscope:\n  - "Q:\\\\Custom"\n---\n\n# Old body\n',
            encoding="utf-8",
        )

        # new_content includes its own front-matter (generated from meta)
        new_content = '---\nsource_root: "Q:\\\\Generated"\n---\n\n# New body\n\nNew content here.\n'
        write_with_frontmatter_preservation(readme, new_content)

        result = readme.read_text(encoding="utf-8")
        # Existing front-matter preserved
        assert 'source_root: "Q:\\\\Custom"' in result
        # New body used
        assert "# New body" in result
        assert "# Old body" not in result
        # Generated front-matter NOT present
        assert "Q:\\\\Generated" not in result

    def test_writes_full_content_when_no_file(self, tmp_path):
        """When file doesn't exist, writes full content as-is."""
        readme = tmp_path / "README.md"
        content = "---\nsource_root: /src\n---\n\n# Body\n"
        write_with_frontmatter_preservation(readme, content)

        result = readme.read_text(encoding="utf-8")
        assert result == content

    def test_writes_full_when_no_frontmatter(self, tmp_path):
        """Existing file without front-matter gets fully replaced."""
        readme = tmp_path / "README.md"
        readme.write_text("# Just a plain file\n", encoding="utf-8")

        new_content = "---\nsource_root: /src\n---\n\n# New\n"
        write_with_frontmatter_preservation(readme, new_content)

        result = readme.read_text(encoding="utf-8")
        assert result == new_content
